name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel Production
        uses: vercel/vercel-action@v3
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_ZwqcatAquvcaHPsyfe2pINuD
          vercel-project-id: prj_ePUg3nGNY7fCfTkCX6NtxBGkX294
          vercel-args: --prod
          working-directory: .
